config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    resources :edits
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/edit.rb
class Edit < ActiveRecord::Base
  belongs_to :story

  validates :text, :presence => true
  validates :creator, :presence => true
  validates :online, :presence => true
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :edits

  validates :name, :presence => true
  validates :creator_name, :presence => true
  validates :image_identifier, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/edits_controller.rb
class EditsController < ApplicationController

def new
  @story = Story.find(params[:story_id])
  @edit = @story.edits.new
  render :new
end


private
  def task_params
    params.require(:edit).permit(:text, :creator, :online, :story_id)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def edit
    @story = Story.find(params[:id])
    render :edit
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      redirect_to stories_path
    else
      render :new
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  def update
    @story= Story.find(params[:id])
    if @story.update(story_params)
      redirect_to story_path
    else
      render :edit
    end
  end

private
  def story_params
    params.require(:story).permit(:name, :creator_name, :image_identifier)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/edits/_form.html.erb
<%= render('layouts/errors', :object => @edit) %>

<%= form_for [@story, @edit] do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.label :creator %>
  <%= f.text_field :creator %>
  <%= f.label :online %>
  <%= f.text_field :online %>
  <p><%= f.submit %></p>
<% end %>

app/views/edits/new.html.erb
<h1>New task for <%= @story.name %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end%>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :creator_name %>
  <%= f.text_field :creator_name %>
  <br>
  <%= f.label :image_identifier %>
  <%= f.text_field :image_identifier %>
  <br>
  <%= f.submit %>
<% end %>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<%= render "form" %>

app/views/stories/index.html.erb
<h1>Stories</h1>

<ul>
  <% @stories.each do |story| %>
    <li><%= link_to story.name, story_path(story) %></li>
  <% end %>
</ul>

<%= link_to "add new story", new_story_path%>

app/views/stories/new.html.erb
<%= form_for @story do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :creator_name %>
  <%= f.text_field :creator_name %>
  <br>
  <%= f.label :image_identifier %>
  <%= f.text_field :image_identifier %>
  <br>
  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<h1><%= @story.name %></h1>
<p><em>By <%= @story.creator_name %> </em></p>

<% if @story.edits.any? %>
  <h4>Here are the edits for this story:</h4>

  <ul>
    <% @story.edits.each do |edit| %>
      <li>
        <%= edit.text %> |
        <%= link_to "Edit", edit_story_edit_path(@story, edit) %> |
        <%= link_to "Delete", story_edit_path(@story, edit),
                                  :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no entries yet!</p>
<% end %>

<p><%= link_to "Add an entry", new_story_edit_path(@story) %></p>
<p><%= link_to "Edit", edit_story_path(@story) %></p>
<p><%= link_to "Delete List", story_path(@story),
                          :data => {:confirm => "Are You Sure?",
                                    :method => "delete"}%></p>

<p><%= link_to "Return to stories", stories_path %></p>